// The guard's shared test vectors: hooks/guard.ts (tests/guard.test.ts)
// and its Go port in the server (internal/server/guardmatch_test.go) both
// pass every case: what the call breaks (rule, null for none) and the
// summary journaled; and the sentence each rule gives each role. The
// tools (each one's kind and input fields, as a manifest's [guard.tools]
// gives them and GET /v1/rules serves them) go with every rule set:
// Claude's and Codex's, which their manifests must match
// (internal/agent TestGuardToolVectors), and a lowercase vocabulary like
// pi's and opencode's. A case the guard asks about rather than refuses
// (a PowerShell command it can't read) has rule "unknown" and "ask": true.
// Everything after "export default " is JSON, for the Go test: keep it
// so (double quotes, no trailing commas, no comments). One case a line.
export default {
"tools": {
 "Bash": {"kind": "shell", "fields": ["command"]},
 "PowerShell": {"kind": "shell", "syntax": "powershell", "fields": ["command"]},
 "Edit": {"kind": "write", "fields": ["file_path"]},
 "Write": {"kind": "write", "fields": ["file_path"]},
 "MultiEdit": {"kind": "write", "fields": ["file_path"]},
 "NotebookEdit": {"kind": "write", "fields": ["notebook_path"]},
 "Read": {"kind": "read", "fields": ["file_path"]},
 "Grep": {"kind": "read", "fields": ["path"]},
 "Glob": {"kind": "glob", "fields": ["pattern", "path"]},
 "apply_patch": {"kind": "patch", "fields": ["command"]},
 "bash": {"kind": "shell", "fields": ["command"]},
 "edit": {"kind": "write", "fields": ["filePath"]},
 "write": {"kind": "write", "fields": ["filePath"]},
 "patch": {"kind": "patch", "fields": ["patchText"]},
 "read": {"kind": "read", "fields": ["filePath"]},
 "grep": {"kind": "read", "fields": ["path"]},
 "glob": {"kind": "glob", "fields": ["pattern", "path"]}
},
"rules": {
 "thread": {"on": true, "role": "thread", "rules": ["force-push", "push-default", "worktree-only", "delete-branch", "merge", "credentials"], "home": "/h", "cwd": "/h/.terminatr/worktrees/demo/t-0001-fix", "writable": ["/h/.terminatr/worktrees/demo/t-0001-fix", "/tmp", "/private/tmp"], "worktrees": "/h/.terminatr/worktrees", "protected": ["main", "master"], "secrets": ["/h/.ssh", "/h/.aws", "/h/.config/gh", "/h/.codex/auth.json", "/ch/auth.json"]},
 "coordinator": {"on": true, "role": "coordinator", "rules": ["force-push", "push-default", "delete-branch", "credentials"], "home": "/h", "cwd": "/h/.terminatr/projects/demo", "worktrees": "/h/.terminatr/worktrees", "protected": ["main", "master"], "secrets": ["/h/.ssh", "/h/.aws", "/h/.config/gh", "/h/.codex/auth.json", "/ch/auth.json"]},
 "thread-no-merge": {"on": true, "role": "thread", "rules": ["force-push", "push-default", "worktree-only", "delete-branch", "credentials"], "home": "/h", "cwd": "/h/.terminatr/worktrees/demo/t-0001-fix", "writable": ["/h/.terminatr/worktrees/demo/t-0001-fix", "/tmp", "/private/tmp"], "worktrees": "/h/.terminatr/worktrees", "protected": ["main", "master"], "secrets": ["/h/.ssh", "/h/.aws", "/h/.config/gh", "/h/.codex/auth.json", "/ch/auth.json"]},
 "thread-casefold": {"on": true, "role": "thread", "rules": ["force-push", "push-default", "worktree-only", "delete-branch", "merge", "credentials"], "home": "/h", "cwd": "/h/.terminatr/worktrees/demo/t-0001-fix", "writable": ["/h/.terminatr/worktrees/demo/t-0001-fix", "/tmp", "/private/tmp"], "worktrees": "/h/.terminatr/worktrees", "protected": ["main", "master"], "secrets": ["/h/.ssh", "/h/.aws", "/h/.config/gh", "/h/.codex/auth.json", "/ch/auth.json"], "caseFold": true},
 "coordinator-casefold": {"on": true, "role": "coordinator", "rules": ["force-push", "push-default", "delete-branch", "credentials"], "home": "/h", "cwd": "/h/.terminatr/projects/demo", "worktrees": "/h/.terminatr/worktrees", "protected": ["main", "master"], "secrets": ["/h/.ssh", "/h/.aws", "/h/.config/gh", "/h/.codex/auth.json", "/ch/auth.json"], "caseFold": true},
 "thread-windows": {"on": true, "role": "thread", "rules": ["force-push", "push-default", "worktree-only", "delete-branch", "merge", "credentials"], "home": "C:\\Users\\me", "cwd": "C:\\Users\\me\\.terminatr\\worktrees\\demo\\t-0001-fix", "writable": ["C:\\Users\\me\\.terminatr\\worktrees\\demo\\t-0001-fix", "C:\\Users\\me\\AppData\\Local\\Temp"], "worktrees": "C:\\Users\\me\\.terminatr\\worktrees", "protected": ["main", "master"], "secrets": ["C:\\Users\\me\\.ssh", "C:\\Users\\me\\.config\\gh", "C:\\Users\\me\\.azure", "C:\\Users\\me\\.codex\\auth.json"], "caseFold": true},
 "off": {"on": false}
},
"cases": [
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push -f"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push --force origin tm/x"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push --force-with-lease"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push -uf origin tm/x"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin +tm/x"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git -C /w push --force"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "FOO=1 git push --force"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "sudo git push --mirror"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin main"}, "rule": "push-default", "summary": "git push to main"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin HEAD:main"}, "rule": "push-default", "summary": "git push to main"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin HEAD:refs/heads/master"}, "rule": "push-default", "summary": "git push to master"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push --all origin"}, "rule": "push-default", "summary": "git push --all"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push -u origin tm/x"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin HEAD"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin main:tm/x"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git status && git push origin tm/x"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git branch -D tm/x"}, "rule": "delete-branch", "summary": "git branch -D"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git branch -d tm/x"}, "rule": "delete-branch", "summary": "git branch --delete"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git branch --delete tm/x"}, "rule": "delete-branch", "summary": "git branch --delete"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin --delete tm/x"}, "rule": "delete-branch", "summary": "git push deleting a branch"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git push origin :tm/x"}, "rule": "delete-branch", "summary": "git push deleting a branch"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git worktree remove ../x"}, "rule": "delete-branch", "summary": "git worktree remove"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git worktree prune"}, "rule": "delete-branch", "summary": "git worktree prune"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh repo delete o/r"}, "rule": "delete-branch", "summary": "gh repo delete"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "rm -rf ."}, "rule": "delete-branch", "summary": "rm -r of /h/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "rm -rf /h/.terminatr/worktrees/demo/t-0001-fix"}, "rule": "delete-branch", "summary": "rm -r of /h/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "rm -r /h/.terminatr/worktrees/demo"}, "rule": "delete-branch", "summary": "rm -r of /h/.terminatr/worktrees/demo"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh api -X DELETE repos/o/r/git/refs/heads/x"}, "rule": "delete-branch", "summary": "gh api deleting a branch"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git branch -a"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git branch tm/new"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "rm -rf build"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "rm -f /h/.terminatr/worktrees/demo/t-0001-fix/x.txt"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git worktree list"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh pr merge 42 --merge"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh api -X PUT repos/o/r/pulls/42/merge"}, "rule": "merge", "summary": "gh api merging a PR"},
 {"rules": "coordinator", "tool": "Bash", "input": {"command": "gh pr merge 42 --merge"}, "rule": null},
 {"rules": "thread-no-merge", "tool": "Bash", "input": {"command": "gh pr merge 42"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh pr view 42 && gh pr checks 42"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --status completed"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --status=completed"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --auto-complete true"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --auto-complete"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --bypass-policy true"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --org=https://dev.azure.com/o --id 7 --status completed"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr create --auto-complete true"}, "rule": "merge", "summary": "az repos pr create completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az --only-show-errors repos pr update --id 7 --status completed"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az -o json repos pr update --id 7 --status Completed"}, "rule": "merge", "summary": "az repos pr update completing a PR"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method patch --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7?api-version=7.1 --body @b.json"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest -m PATCH -u https://dev.azure.com/o/p/_apis/git/repositories/r/pullRequests/7"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method post --url https://dev.azure.com/o/p/_apis/git/repositories/r/merges"}, "rule": "merge", "summary": "POST on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az devops invoke --area git --resource pullRequests --http-method PATCH --route-parameters project=p repositoryId=r pullRequestId=7"}, "rule": "merge", "summary": "az devops invoke PATCH on pullrequests"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl -X PATCH https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7 -d @b.json"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method patch --resource 499b84ac-1321-427f-aa17-267ca6975798 --url 'https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7?api-version=7.1' --body '{\"status\":\"completed\"}'"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --resource 499b84ac-1321-427f-aa17-267ca6975798 -m patch -u https://dev.azure.com/o/_apis/git/pullrequests/7?api-version=7.1 --body @b.json"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7 --headers Accept=application/json X-HTTP-Method-Override=PATCH --body @b.json"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos delete --id r --yes"}, "rule": "delete-branch", "summary": "az repos delete"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos ref delete --name refs/heads/x --object-id abc"}, "rule": "delete-branch", "summary": "az repos ref delete"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --delete-source-branch true"}, "rule": "delete-branch", "summary": "az repos pr update --delete-source-branch"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr create --delete-source-branch true"}, "rule": "delete-branch", "summary": "az repos pr create --delete-source-branch"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method delete --url https://dev.azure.com/o/p/_apis/git/repositories/r"}, "rule": "delete-branch", "summary": "DELETE on an Azure DevOps ref or repository"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method post --url https://dev.azure.com/o/p/_apis/git/repositories/r/refs --body @zero.json"}, "rule": "delete-branch", "summary": "POST on an Azure DevOps ref or repository"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az devops invoke --area git --resource refs --http-method POST --route-parameters project=p repositoryId=r --in-file z.json"}, "rule": "delete-branch", "summary": "az devops invoke POST on refs"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl --request DELETE https://dev.azure.com/o/p/_apis/git/repositories/r"}, "rule": "delete-branch", "summary": "DELETE on an Azure DevOps ref or repository"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl -XPOST https://dev.azure.com/o/p/_apis/git/repositories/r/refs"}, "rule": "delete-branch", "summary": "POST on an Azure DevOps ref or repository"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az account get-access-token"}, "rule": "credentials", "summary": "az account get-access-token"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798"}, "rule": "credentials", "summary": "az account get-access-token"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az devops login --organization https://dev.azure.com/o"}, "rule": "credentials", "summary": "az devops login"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "echo $AZURE_DEVOPS_EXT_PAT"}, "rule": "credentials", "summary": "echo of AZURE_DEVOPS_EXT_PAT"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "echo \"pat: ${AZURE_DEVOPS_EXT_PAT}\""}, "rule": "credentials", "summary": "echo of AZURE_DEVOPS_EXT_PAT"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv AZURE_DEVOPS_EXT_PAT"}, "rule": "credentials", "summary": "printenv AZURE_DEVOPS_EXT_PAT"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl -u :$AZURE_DEVOPS_EXT_PAT https://dev.azure.com/o/_apis/projects"}, "rule": "credentials", "summary": "an HTTP call to Azure DevOps with credentials"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl -H \"Authorization: Basic abc\" https://dev.azure.com/o/_apis/projects"}, "rule": "credentials", "summary": "an HTTP call to Azure DevOps with credentials"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl --user me:pat https://o.visualstudio.com/_apis/projects"}, "rule": "credentials", "summary": "an HTTP call to Azure DevOps with credentials"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr list --status completed"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr show --id 7"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr create --title t --source-branch tm/x --target-branch main"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr create --auto-complete false --delete-source-branch false"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --description d"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --status abandoned"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr set-vote --id 7 --vote approve"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos pr list --status active"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos list"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az repos ref list --filter heads/tm"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az account show"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az devops configure --defaults organization=https://dev.azure.com/o"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az pipelines runs list"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method get --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method post --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests --body @pr.json"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method post --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7/threads --body @c.json"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az devops invoke --area git --resource pullRequests --route-parameters project=p repositoryId=r pullRequestId=7"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az devops invoke --area git --resource pullRequestThreads --http-method POST --route-parameters pullRequestId=7"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "curl https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv AZURE_CONFIG_DIR"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "echo $HOME"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method get --resource 499b84ac-1321-427f-aa17-267ca6975798 --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7?api-version=7.1 --headers Accept=application/json"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --resource 499b84ac-1321-427f-aa17-267ca6975798 --url 'https://dev.azure.com/o/p/_apis/build/builds?branchName=refs/pull/7/merge&api-version=7.1' --query 'value[].{build:id,status:status,result:result}' -o table"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --resource 499b84ac-1321-427f-aa17-267ca6975798 --url 'https://dev.azure.com/o/p/_apis/git/repositories/r/pullRequests/7/threads?api-version=7.1' --query \"value[].comments[?commentType=='text'][].{author:author.displayName,text:content}\" -o table"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "az rest --method post --resource 499b84ac-1321-427f-aa17-267ca6975798 --url https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests?api-version=7.1 --body @pr.json"}, "rule": null},
 {"rules": "coordinator", "tool": "Bash", "input": {"command": "az repos pr update --id 7 --status completed"}, "rule": null},
 {"rules": "coordinator", "tool": "Bash", "input": {"command": "az repos delete --id r"}, "rule": "delete-branch", "summary": "az repos delete"},
 {"rules": "thread", "tool": "Edit", "input": {"file_path": "/h/.terminatr/worktrees/demo/t-0001-fix/main.go"}, "rule": null},
 {"rules": "thread", "tool": "Write", "input": {"file_path": "/tmp/claude-501/x/notes.md"}, "rule": null},
 {"rules": "thread", "tool": "Write", "input": {"file_path": "docs/a.md"}, "rule": null},
 {"rules": "thread", "tool": "Edit", "input": {"file_path": "/h/.terminatr/projects/demo/PROJECT.md"}, "rule": "worktree-only", "summary": "Edit of /h/.terminatr/projects/demo/PROJECT.md"},
 {"rules": "thread", "tool": "Write", "input": {"file_path": "/h/.terminatr/worktrees/demo/t-0001-fix/../other/x"}, "rule": "worktree-only", "summary": "Write of /h/.terminatr/worktrees/demo/other/x"},
 {"rules": "thread", "tool": "NotebookEdit", "input": {"notebook_path": "/h/n.ipynb"}, "rule": "worktree-only", "summary": "NotebookEdit of /h/n.ipynb"},
 {"rules": "coordinator", "tool": "Edit", "input": {"file_path": "/h/.terminatr/projects/demo/TASKS.md"}, "rule": null},
 {"rules": "thread", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Add File: hello.txt\n+hi\n*** End Patch"}, "rule": null},
 {"rules": "thread", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Update File: /h/.terminatr/worktrees/demo/t-0001-fix/main.go\n@@\n-hi\n+bye\n*** End Patch"}, "rule": null},
 {"rules": "thread", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Update File: /tmp/x/notes.md\n@@\n-a\n+b\n*** End Patch"}, "rule": null},
 {"rules": "thread", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Update File: /h/.terminatr/projects/demo/TASKS.md\n@@\n-a\n+b\n*** End Patch"}, "rule": "worktree-only", "summary": "apply_patch of /h/.terminatr/projects/demo/TASKS.md"},
 {"rules": "thread", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Update File: a.go\n*** Move to: ../other/a.go\n@@\n-a\n+b\n*** End Patch"}, "rule": "worktree-only", "summary": "apply_patch of /h/.terminatr/worktrees/demo/other/a.go"},
 {"rules": "thread", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Delete File: ~/.zshrc\n*** End Patch"}, "rule": "worktree-only", "summary": "apply_patch of /h/.zshrc"},
 {"rules": "coordinator", "tool": "apply_patch", "input": {"command": "*** Begin Patch\n*** Update File: /h/.terminatr/projects/demo/TASKS.md\n@@\n-a\n+b\n*** End Patch"}, "rule": null},
 {"rules": "thread", "tool": "Read", "input": {"file_path": "/h/.ssh/id_ed25519"}, "rule": "credentials", "summary": "Read of /h/.ssh/id_ed25519"},
 {"rules": "coordinator", "tool": "Grep", "input": {"pattern": "token", "path": "/h/.config/gh"}, "rule": "credentials", "summary": "Grep of /h/.config/gh"},
 {"rules": "thread", "tool": "Glob", "input": {"pattern": "/h/.aws/*"}, "rule": "credentials", "summary": "Glob of /h/.aws/?"},
 {"rules": "thread", "tool": "Read", "input": {"file_path": "/h/.terminatr/worktrees/demo/t-0001-fix/README.md"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "cat ~/.ssh/id_rsa"}, "rule": "credentials", "summary": "cat of /h/.ssh/id_rsa"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "base64 < $HOME/.aws/credentials"}, "rule": "credentials", "summary": "base64 of /h/.aws/credentials"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "cat ~/.codex/auth.json"}, "rule": "credentials", "summary": "cat of /h/.codex/auth.json"},
 {"rules": "coordinator", "tool": "Read", "input": {"file_path": "/ch/auth.json"}, "rule": "credentials", "summary": "Read of /ch/auth.json"},
 {"rules": "thread", "tool": "Read", "input": {"file_path": "/h/.codex/config.toml"}, "rule": null},
 {"rules": "thread", "tool": "bash", "input": {"command": "cd x && gh pr merge 1"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "bash", "input": {"command": "git push -u origin tm/x"}, "rule": null},
 {"rules": "thread", "tool": "edit", "input": {"filePath": "/h/.terminatr/projects/demo/PROJECT.md"}, "rule": "worktree-only", "summary": "edit of /h/.terminatr/projects/demo/PROJECT.md"},
 {"rules": "thread", "tool": "write", "input": {"filePath": "docs/a.md"}, "rule": null},
 {"rules": "thread", "tool": "write", "input": {"file_path": "/etc/x"}, "rule": null},
 {"rules": "thread", "tool": "patch", "input": {"patchText": "*** Begin Patch\n*** Update File: /etc/hosts\n@@\n-a\n+b\n*** End Patch"}, "rule": "worktree-only", "summary": "patch of /etc/hosts"},
 {"rules": "thread", "tool": "patch", "input": {"patchText": "*** Begin Patch\n*** Add File: x.go\n+package x\n*** End Patch"}, "rule": null},
 {"rules": "thread", "tool": "read", "input": {"filePath": "/h/.ssh/id_ed25519"}, "rule": "credentials", "summary": "read of /h/.ssh/id_ed25519"},
 {"rules": "thread", "tool": "read", "input": {"filePath": "README.md"}, "rule": null},
 {"rules": "coordinator", "tool": "grep", "input": {"pattern": "token", "path": "/h/.config/gh"}, "rule": "credentials", "summary": "grep of /h/.config/gh"},
 {"rules": "thread", "tool": "glob", "input": {"pattern": "/h/.aws/*"}, "rule": "credentials", "summary": "glob of /h/.aws/?"},
 {"rules": "thread", "tool": "Glob", "input": {"pattern": "*.json", "path": "/h/.aws"}, "rule": "credentials", "summary": "Glob of /h/.aws"},
 {"rules": "thread", "tool": "shell", "input": {"command": "gh pr merge 1"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"cmd": "gh pr merge 1"}, "rule": null},
 {"rules": "off", "tool": "bash", "input": {"command": "gh pr merge 1"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh auth token"}, "rule": "credentials", "summary": "gh auth token"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh auth status --show-token"}, "rule": "credentials", "summary": "gh auth status --show-token"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "security find-generic-password -s x -w"}, "rule": "credentials", "summary": "security find-generic-password"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv"}, "rule": "credentials", "summary": "printenv printing the environment"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv -0"}, "rule": "credentials", "summary": "printenv printing the environment"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv PATH GITHUB_TOKEN"}, "rule": "credentials", "summary": "printenv GITHUB_TOKEN"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv aws_secret_access_key"}, "rule": "credentials", "summary": "printenv aws_secret_access_key"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv MY_PASSWORD"}, "rule": "credentials", "summary": "printenv MY_PASSWORD"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "env"}, "rule": "credentials", "summary": "env printing the environment"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "env | grep TOKEN"}, "rule": "credentials", "summary": "env printing the environment"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git credential fill"}, "rule": "credentials", "summary": "git credential fill"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "gh auth status"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "cat README.md"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "env GOOS=linux go build ./..."}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv HOME"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv HOME PATH TERM"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "printenv -0 SHELL"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "ssh -T git@github.com"}, "rule": null},
 {"rules": "off", "tool": "Bash", "input": {"command": "git push -f origin main"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "echo \"a $(gh pr merge 3) b\" | cat"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "x=`gh pr merge 3`"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "(cd x; gh pr merge 3)"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git status\ngh pr merge 3"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "nohup gh pr merge 3 &"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "env -i FOO=1 gh pr merge 3"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "/usr/local/bin/gh pr merge 3"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "g\\h pr merge 3"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "'gh' pr 'merge' 3"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "echo 'gh pr merge 3'"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git commit -m \"push --force later\""}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git -c user.name=x push --force"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "git --git-dir=.git push -f"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "time git push --force-if-includes"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "cat < ~/.ssh/id_rsa"}, "rule": "credentials", "summary": "cat of /h/.ssh/id_rsa"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "cat <~/.ssh/id_rsa"}, "rule": "credentials", "summary": "cat of /h/.ssh/id_rsa"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "grep -r key /h/.aws"}, "rule": "credentials", "summary": "grep of /h/.aws"},
 {"rules": "thread", "tool": "Bash", "input": {"command": "security dump-keychain"}, "rule": "credentials", "summary": "security dump-keychain"},
 {"rules": "coordinator", "tool": "Bash", "input": {"command": "rm -rf ~/.Terminatr/worktrees"}, "rule": null},
 {"rules": "coordinator-casefold", "tool": "Bash", "input": {"command": "rm -rf ~/.Terminatr/worktrees"}, "rule": "delete-branch", "summary": "rm -r of /h/.Terminatr/worktrees"},
 {"rules": "coordinator-casefold", "tool": "Bash", "input": {"command": "rm -rf /H/.TERMINATR"}, "rule": "delete-branch", "summary": "rm -r of /H/.TERMINATR"},
 {"rules": "coordinator-casefold", "tool": "Bash", "input": {"command": "rm -r /h/.terminatr/Worktrees/Demo/T-0001-fix"}, "rule": "delete-branch", "summary": "rm -r of /h/.terminatr/Worktrees/Demo/T-0001-fix"},
 {"rules": "coordinator-casefold", "tool": "Bash", "input": {"command": "rm -r /h/.terminatr/Worktrees/demo/t-0001-fix/Build"}, "rule": null},
 {"rules": "thread-casefold", "tool": "Bash", "input": {"command": "rm -rf /h/.terminatr/worktrees/demo/T-0001-FIX"}, "rule": "delete-branch", "summary": "rm -r of /h/.terminatr/worktrees/demo/T-0001-FIX"},
 {"rules": "thread", "tool": "Read", "input": {"file_path": "/h/.SSH/id_rsa"}, "rule": null},
 {"rules": "thread-casefold", "tool": "Read", "input": {"file_path": "/h/.SSH/id_rsa"}, "rule": "credentials", "summary": "Read of /h/.SSH/id_rsa"},
 {"rules": "thread-casefold", "tool": "Bash", "input": {"command": "cat ~/.Aws/credentials"}, "rule": "credentials", "summary": "cat of /h/.Aws/credentials"},
 {"rules": "thread-casefold", "tool": "Glob", "input": {"pattern": "/H/*"}, "rule": null},
 {"rules": "thread-casefold", "tool": "Glob", "input": {"pattern": "/h/.Config/*"}, "rule": "credentials", "summary": "Glob of /h/.Config/?"},
 {"rules": "thread", "tool": "Write", "input": {"file_path": "/h/.terminatr/worktrees/demo/T-0001-FIX/main.go"}, "rule": "worktree-only", "summary": "Write of /h/.terminatr/worktrees/demo/T-0001-FIX/main.go"},
 {"rules": "thread-casefold", "tool": "Write", "input": {"file_path": "/h/.terminatr/worktrees/demo/T-0001-FIX/main.go"}, "rule": null},
 {"rules": "thread-casefold", "tool": "Write", "input": {"file_path": "/h/.terminatr/worktrees/demo/t-0002-other/main.go"}, "rule": "worktree-only", "summary": "Write of /h/.terminatr/worktrees/demo/t-0002-other/main.go"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git push --force origin tm/x"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "cd C:\\w; git push -f"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$out = git push -f 2>&1"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "[string]$out=git push -f"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "& \"C:\\Program Files\\Git\\cmd\\git.exe\" push --force"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Git.exe push origin main"}, "rule": "push-default", "summary": "git push to main"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git push `\n  origin main"}, "rule": "push-default", "summary": "git push to main"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git status && gh pr merge 42"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git status; if ($?) { gh pr merge 42 }"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Write-Output \"merged: $(gh pr merge 42)\""}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$body = @\"\nmerged $(gh pr merge 42)\n\"@"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$body = @'\nno $(gh pr merge 42)\n'@"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git branch --list | ForEach-Object { git branch -D $_ }"}, "rule": "delete-branch", "summary": "git branch -D"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "& { gh pr merge 1 }"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git log # git push -f"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "<# git push -f #> git status"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "echo 'git push -f'"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "echo \"it''s `\"gh pr merge`\" \""}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Remove-Item -Recurse -Force ."}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of /h/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "ri -r /h/.terminatr/worktrees/demo"}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of /h/.terminatr/worktrees/demo"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Remove-Item –Recurse ..\\t-0001-fix"}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of /h/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "rm.exe -rf build, ."}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of /h/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Remove-Item -Recurse build"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Remove-Item . -Recurse:$false"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Get-Content ~\\.ssh\\id_rsa"}, "rule": "credentials", "summary": "get-content of /h/.ssh/id_rsa"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "gc $env:USERPROFILE\\.aws\\credentials"}, "rule": "credentials", "summary": "gc of /h/.aws/credentials"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Copy-Item -Path:$HOME/.config/gh/hosts.yml ."}, "rule": "credentials", "summary": "copy-item of /h/.config/gh/hosts.yml"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Get-ChildItem env:"}, "rule": "credentials", "summary": "get-childitem printing the environment"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "dir env:*"}, "rule": "credentials", "summary": "dir printing the environment"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Get-Item Env:GITHUB_TOKEN"}, "rule": "credentials", "summary": "get-item of GITHUB_TOKEN"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Get-ChildItem Env:PATH"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$env:AZURE_DEVOPS_EXT_PAT"}, "rule": "credentials", "summary": "output of AZURE_DEVOPS_EXT_PAT"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Write-Host \"pat: $env:AZURE_DEVOPS_EXT_PAT\""}, "rule": "credentials", "summary": "write-host of AZURE_DEVOPS_EXT_PAT"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$pat = $env:AZURE_DEVOPS_EXT_PAT"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$env:Path"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "gh auth token"}, "rule": "credentials", "summary": "gh auth token"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Invoke-RestMethod -Uri https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7?api-version=7.1 -Method Patch -Body $b"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "irm https://dev.azure.com/o/p/_apis/git/repositories/r/refs -Method:POST"}, "rule": "delete-branch", "summary": "POST on an Azure DevOps ref or repository"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "iwr https://dev.azure.com/o/_apis/git/repositories/r -Headers @{Authorization = \"Basic $x\"}"}, "rule": "credentials", "summary": "an HTTP call to Azure DevOps with credentials"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "curl https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests/7 -Method Patch"}, "rule": "merge", "summary": "PATCH on an Azure DevOps pull request"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Invoke-RestMethod https://dev.azure.com/o/p/_apis/git/repositories/r/pullrequests"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "pwsh -NoProfile -Command \"gh pr merge 1\""}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "powershell -ExecutionPolicy Bypass -c 'git push -f'"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "powershell.exe -NoLogo 'gh pr merge 1'"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "pwsh -File .\\build.ps1"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "cmd /c \"git push -f\""}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "bash -lc 'gh pr merge 1'"}, "rule": "merge", "summary": "gh pr merge"},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Invoke-Expression 'git status'"}, "rule": "unknown", "summary": "invoke-expression", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "$cmd | iex"}, "rule": "unknown", "summary": "iex", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "& $git push"}, "rule": "unknown", "summary": "& of a variable", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": ". $PROFILE"}, "rule": "unknown", "summary": ". of a variable", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "& (Get-Command gh) pr merge 1"}, "rule": "unknown", "summary": "& of an expression", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "pwsh -EncodedCommand ZwBpAHQA"}, "rule": "unknown", "summary": "an encoded command", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Start-Process git -ArgumentList 'push','-f'"}, "rule": "unknown", "summary": "start-process", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Set-Alias g git; g push -f"}, "rule": "unknown", "summary": "set-alias", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "[Diagnostics.Process]::Start('git', 'push -f')"}, "rule": "unknown", "summary": "the .Start() method", "ask": true},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Invoke-Expression 'x'; git push -f"}, "rule": "force-push", "summary": "git push with force"},
 {"rules": "coordinator", "tool": "PowerShell", "input": {"command": "iex 'git status'"}, "rule": "unknown", "summary": "iex", "ask": true},
 {"rules": "off", "tool": "PowerShell", "input": {"command": "iex 'git push -f'"}, "rule": null},
 {"rules": "thread", "tool": "Bash", "input": {"command": "iex 'git push -f'"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "git push -u origin tm/x"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Get-ChildItem -Recurse | Select-String foo"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "go test ./... 2>&1 | Out-File $env:TEMP\\x.txt"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": "Start-Sleep 1 &"}, "rule": null},
 {"rules": "thread", "tool": "PowerShell", "input": {"command": ". .\\env.ps1"}, "rule": null},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "Remove-Item -Recurse -Force C:\\Users\\me\\.terminatr\\worktrees\\demo\\t-0001-fix"}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of C:/Users/me/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "Remove-Item -Recurse -Force c:\\users\\ME\\.Terminatr\\worktrees"}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of c:/users/ME/.Terminatr/worktrees"},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "rm -r -fo ."}, "rule": "delete-branch", "summary": "Remove-Item -Recurse of C:/Users/me/.terminatr/worktrees/demo/t-0001-fix"},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "Remove-Item -Recurse D:\\other"}, "rule": null},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "Get-Content $env:USERPROFILE\\.ssh\\id_ed25519"}, "rule": "credentials", "summary": "get-content of C:/Users/me/.ssh/id_ed25519"},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "type ~/.SSH/config"}, "rule": "credentials", "summary": "type of C:/Users/me/.SSH/config"},
 {"rules": "thread-windows", "tool": "PowerShell", "input": {"command": "Get-Content README.md"}, "rule": null},
 {"rules": "thread-windows", "tool": "Edit", "input": {"file_path": "C:\\Users\\me\\.terminatr\\worktrees\\demo\\t-0001-fix\\main.go"}, "rule": null},
 {"rules": "thread-windows", "tool": "Edit", "input": {"file_path": "C:\\Users\\me\\.terminatr\\projects\\demo\\PROJECT.md"}, "rule": "worktree-only", "summary": "Edit of C:/Users/me/.terminatr/projects/demo/PROJECT.md"},
 {"rules": "thread-windows", "tool": "Write", "input": {"file_path": "c:/users/me/appdata/local/temp/x.txt"}, "rule": null},
 {"rules": "thread-windows", "tool": "Write", "input": {"file_path": "docs\\a.md"}, "rule": null},
 {"rules": "thread-windows", "tool": "Read", "input": {"file_path": "C:\\Users\\me\\.azure\\msal_token_cache.json"}, "rule": "credentials", "summary": "Read of C:/Users/me/.azure/msal_token_cache.json"},
 {"rules": "thread-windows", "tool": "Glob", "input": {"pattern": "C:\\*"}, "rule": null},
 {"rules": "thread-windows", "tool": "Glob", "input": {"pattern": "C:\\Users\\me\\.config\\*"}, "rule": "credentials", "summary": "Glob of C:/Users/me/.config/?"}
],
"messages": {
 "thread": {
  "force-push": "terminatr guard (force-push): force-pushing is not allowed here. Push without force; if the branch has diverged, merge instead of rewriting it, or say so in your report.",
  "push-default": "terminatr guard (push-default): nothing is pushed straight to master: work lands through a pull request. Push your own branch and open a PR.",
  "worktree-only": "terminatr guard (worktree-only): a thread writes only inside its worktree (/h/.terminatr/worktrees/demo/t-0001-fix). Write the file there, or say so in your report what needs changing elsewhere.",
  "delete-branch": "terminatr guard (delete-branch): agents don't delete branches or worktrees; tm cleans them up once the work has merged. Leave them, and say so in your report if one is in the way.",
  "merge": "terminatr guard (merge): merging is the coordinator's job in this project (merge = \"coordinator\"). Leave the PR open with CI green and say so in your report.",
  "credentials": "terminatr guard (credentials): credential files and tokens are not read here. If the task needs access you don't have, say so in your report exactly what is missing."
 },
 "coordinator": {
  "force-push": "terminatr guard (force-push): force-pushing is not allowed here. Push without force; if the branch has diverged, merge instead of rewriting it, or ask the user.",
  "push-default": "terminatr guard (push-default): nothing is pushed straight to master: work lands through a pull request. Push your own branch and open a PR.",
  "worktree-only": "terminatr guard (worktree-only): a thread writes only inside its worktree (/h/.terminatr/worktrees/demo/t-0001-fix). Write the file there, or ask the user what needs changing elsewhere.",
  "delete-branch": "terminatr guard (delete-branch): agents don't delete branches or worktrees; tm cleans them up once the work has merged. Leave them, and ask the user if one is in the way.",
  "merge": "terminatr guard (merge): merging is the coordinator's job in this project (merge = \"coordinator\"). Leave the PR open with CI green and say so in your report.",
  "credentials": "terminatr guard (credentials): credential files and tokens are not read here. If the task needs access you don't have, ask the user exactly what is missing."
 }
}
}
