package ticker

// Keeping up with the default branch (docs/SPEC.md §7.5): the user's
// own checkouts are fast-forwarded when that is safe, and threads whose
// open PR falls behind or conflicts after main moves are told, once per
// head.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"time"

	"github.com/theclifmeister/termilator/internal/caller"
	"github.com/theclifmeister/termilator/internal/config"
	"github.com/theclifmeister/termilator/internal/project"
	"github.com/theclifmeister/termilator/internal/proto"
	"github.com/theclifmeister/termilator/internal/thread"
	"github.com/theclifmeister/termilator/internal/worktree"
)

func (t *Ticker) projectMemo(slug string) *projectMemo {
	pm := t.st.Projects[slug]
	if pm == nil {
		pm = &projectMemo{}
		t.st.Projects[slug] = pm
	}
	return pm
}

// repos are a project's repos and its unresolved threads' repos, cleaned
// and sorted, once each.
func repos(p *project.Project) []string {
	set := map[string]bool{}
	for _, r := range p.Meta.Repos {
		set[filepath.Clean(r)] = true
	}
	if recs, err := thread.List(p); err == nil {
		for _, r := range recs {
			if r.Repo != "" && r.State != thread.Resolved {
				set[filepath.Clean(r.Repo)] = true
			}
		}
	}
	out := make([]string, 0, len(set))
	for r := range set {
		out = append(out, r)
	}
	sort.Strings(out)
	return out
}

// syncRepos fetches each repo of the project every PRPoll, and at once
// after one of its PRs merged, and fast-forwards the user's checkout when
// fast_forward_checkout allows and it is safe (worktree.Sync). Each
// fast-forward is journaled as caller ticker. It reports whether it
// synced.
func (t *Ticker) syncRepos(p *project.Project, safety config.Safety, now time.Time, merged bool) bool {
	pm := t.projectMemo(p.Slug)
	if !merged && now.Sub(pm.Synced) < t.o.PRPoll {
		return false
	}
	pm.Synced = now
	list := repos(p)
	old := pm.Repos
	pm.Repos = map[string]*repoMemo{}
	for _, repo := range list {
		c, err := t.o.Sync(repo, safety.FastForwardCheckout)
		if err != nil {
			t.o.Log.Printf("ticker: %s: sync %s: %v", p.Slug, repo, err)
		}
		if c.Branch == "" || c.Origin == "" {
			// No origin, or the fetch failed: keep what the last sync saw.
			if prev := old[repo]; prev != nil && err != nil {
				pm.Repos[repo] = prev
			}
			continue
		}
		rm := &repoMemo{Checkout: c}
		if prev := old[repo]; prev != nil && prev.Origin == c.Origin {
			rm.MergedPR = prev.MergedPR
		} else {
			rm.MergedPR = worktree.MergedPR(repo, c.Origin)
		}
		pm.Repos[repo] = rm
		if c.From != "" {
			detail := fmt.Sprintf("%s %s..%s", c.Branch, short(c.From), short(c.To))
			if err := p.Journal(caller.Caller{Kind: caller.Ticker}, "repo.fast-forward", repo, detail); err != nil {
				t.o.Log.Printf("ticker: %s: journal: %v", p.Slug, err)
			}
			t.o.Log.Printf("ticker: %s: fast-forwarded %s %s", p.Slug, repo, detail)
		}
	}
	return true
}

func short(oid string) string {
	if len(oid) > 7 {
		return oid[:7]
	}
	return oid
}

// followMain checks each open thread PR against its repo's default
// branch head once per head: one that is behind or conflicts gets a
// fixed prompt when pr_followup is on and its session runs, and a
// conflict raises a pr-conflict item for the coordinator.
func (t *Ticker) followMain(p *project.Project, sessions []proto.SessionInfo, safety config.Safety) {
	pm := t.projectMemo(p.Slug)
	if len(pm.Repos) == 0 {
		return
	}
	recs, err := thread.List(p)
	if err != nil {
		return
	}
	for _, r := range recs {
		m := t.st.Threads[p.Slug+"/"+r.ID]
		if r.State == thread.Resolved || r.Repo == "" || m == nil || m.PR.State != "OPEN" {
			continue
		}
		rm := pm.Repos[filepath.Clean(r.Repo)]
		if rm == nil || m.MainSeen == rm.Origin || (m.PR.Base != "" && m.PR.Base != rm.Branch) {
			continue
		}
		state, ok := worktree.HeadState(r.Repo, m.PR.Head, rm.Origin)
		if !ok {
			// The commits aren't here: go by what GitHub said.
			switch {
			case m.PR.Mergeable == "CONFLICTING" || m.PR.MergeState == "DIRTY":
				state = "conflict"
			case m.PR.MergeState == "BEHIND":
				state = "behind"
			case m.PR.Mergeable == "MERGEABLE":
			default:
				continue // GitHub hasn't worked it out yet: ask again later
			}
		}
		m.MainSeen = rm.Origin
		if state == "" {
			continue
		}
		moved := rm.Branch + " moved to " + short(rm.Origin)
		if rm.MergedPR > 0 {
			moved += " (#" + strconv.Itoa(rm.MergedPR) + " merged)"
		}
		how := "is behind it"
		if state == "conflict" {
			how = "conflicts with it"
		}
		ref := m.PR.ref()
		_, _, info, live := liveState(r, sessions)
		prompted := false
		if safety.PRFollowup && live {
			text := fmt.Sprintf("[tm] %s, and your %s %s. Merge origin/%s into your branch (no rebase, no force-push), fix any conflicts, rerun the tests, push, and hand in your report again with tm report once CI is green. (Generated by tm.)",
				moved, ref, how, rm.Branch)
			if err := t.o.Host.Prompt(info.ID, text); err != nil {
				t.o.Log.Printf("ticker: %s: main follow-up for %s: %v", p.Slug, r.ID, err)
			} else {
				prompted = true
			}
		}
		if state == "conflict" {
			after := "; the thread was asked to merge it"
			if !prompted {
				after = "; the thread was not prompted (tm thread restart " + r.ID + ", or tell it)"
			}
			t.item(p, KindPRConflict, r.ID, fmt.Sprintf("%s of %s conflicts with %s at %s%s", ref, r.ID, rm.Branch, short(rm.Origin), after), false)
		}
	}
}

// Seen is what the ticker last saw for project slug, from its state
// file at path, for project.Context: PR state lines and checkout notes.
func Seen(path, slug string) project.Ticked {
	return project.Ticked{PRs: Summaries(path, slug), Checkouts: Checkouts(path, slug)}
}

// Checkouts are the notes on project slug's checkouts that are behind
// origin (worktree.Checkout's Note), by repo path, from the state file
// at path. A missing file gives none.
func Checkouts(path, slug string) map[string]string {
	out := map[string]string{}
	b, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	var st state
	if json.Unmarshal(b, &st) != nil {
		return out
	}
	pm := st.Projects[slug]
	if pm == nil {
		return out
	}
	for repo, rm := range pm.Repos {
		if rm == nil {
			continue
		}
		// The file is read back: only a well-formed branch and one of the
		// fixed reasons go into the note.
		c := rm.Checkout
		if !worktree.ValidBranch(c.Branch) || !heldWords[c.Held] {
			continue
		}
		if n := c.Note(); n != "" {
			out[repo] = n
		}
	}
	return out
}

var heldWords = map[string]bool{"": true, worktree.HeldOff: true, worktree.HeldOther: true,
	worktree.HeldDirty: true, worktree.HeldDiverged: true, worktree.HeldRefused: true}
